### ISSUE TITLE
Separate `NDLC.CLI` into to projects?

### ISSUE THREAD

**Issue by joemphilips** [dgarage/NDLC#2]
I've been using this library to practice creating GUI application with Avalonia.

And I want it to work as same as `NDLC.CLI` everything besides user interface itself.
But since some classes are included in `NDLC.CLi`, I have to reference that instead of `NDLC` itself, especially json/repository related things.

I don't want to reference `NDLC.CLi` , infact I can't because I want to use `netcoreapp3.0`  instead of 3.1.

So could you separate `NDLC.CLI` into two and put DTO's and repository into independent project? (Maybe `NDLC.Infrastructure` or `NDLC.IO`?) and make it netstandard compatible? or at least support older netcoreapp version?

**Comment by NicolasDorier** [comment]
@joemphilips I don't want NDLC.Infrastructure and NDLC.IO, but you can move everything you want in a library from CLI to NDLC, then I can make a library out of it.

But my guess is that by using CLI/NDLC, you will have more improvement to suggest, so it does not make too much sense making a library for now.

I would advise you to first reference NDLC directly as a project in your own project.
Move everything you need out of CLI and into NDLC, then make a PR for that.
And as you need to refactor NDLC for your own need, make PR as you go.

I will make a library when it stabilize (also I am not following any spec for now, so some messages will change soon)

**Comment by joemphilips** [comment]
> I would advise you to first reference NDLC directly as a project in your own project.
Move everything you need out of CLI and into NDLC, then make a PR for that.
And as you need to refactor NDLC for your own need, make PR as you go.

Thanks, fair enough. I also might delay my work until it gets more stable.

**Comment by NicolasDorier** [comment]
@joemphilips I think you can start your work, the user flow will be the same. It is just the message that will change.
